### ISSUE TITLE
"based on"

### ISSUE THREAD

**Issue by srl295** [pxpm/github-tag-action#5]
does it have code from the other project? 

if so you might want to include attribution for the other project's authors: https://github.com/tvdias/github-tagger/graphs/contributors

a cleaner way to do it would be to _fork_ that other repo, that would clearly show what changes were yours.

**Comment by pxpm** [comment]
I tried the fork way, the project was based on a boilerplate (same I used), so even the boilerplate code needed changes etc. 

It was just easy for me just to start over from the boilerplate again, and copy the code from the other project. 

Like I told you I am not proeficiente with typescript, I just had a project using the old version, and I needed an updated version. 

I've updated the readme to also include the the link to that contributors page. 

![image](https://github.com/pxpm/github-tag-action/assets/7188159/bae25076-3c56-4c7d-8c00-65af913e46c9)

If you have a better suggestion or any improvements feel free to send a PR. 
The only maintenance I plan to do on this package is to keep it running on github actions for the projects where I am using it, while I am using it.

Cheers and thanks for the heads up 🙏
